version: '3.1'

services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: my-learning
    ports:
      - "5432:5432"
  redis:
    image: redis
    ports:
      - "6379:6379"
